name: elm-ps-bridge
license: MIT

dependencies:
  - base
  - bytestring
  - yaml
  - aeson
  - vector
  - relude
  - optparse-generic
  - purescript-bridge
  - aeson
  - elm-bridge
  - mtl
  - containers
  - text
  - unordered-containers

executable:
  main: Main.hs
  source-dirs: src

default-extensions:
  - NoImplicitPrelude
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MonoLocalBinds
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedStrings
  - PartialTypeSignatures
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns
